name: powerbank
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  #UI
  google_fonts: ^6.3.1
  flutter_svg: ^2.0.17

  #Navigation
  auto_route: ^10.0.1

  #DI
  get_it: ^8.0.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/